version: 0.0
os: linux
files:
- source: /
destination: /var/www/laravel-test/
hooks:
ApplicationStop:
- location: scripts/stop_server.sh
timeout: 300
runas: root
AfterInstall:
- location: scripts/setpermission.sh
timeout: 300
runas: root
ApplicationStart:
- location: scripts/start_server.sh
timeout: 300
runas: root
