version: 0.2

phases:
  pre_build:
    commands:
      - echo preBuild
  build:
    commands:
      - echo Build
      - cd laravel-test
      - php artisan key:generate
      - composer install
      - vendor/bin/phpunit
