version: 0.2

phases:
  install:
    runtime-versions:
      php: latest
  pre_build:
    commands:
      - echo preBuild
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php ;
      - mv composer.phar /usr/bin/composer
      - php -v
  build:
    commands:
      - echo Build
      - composer install
      - composer update
      - echo APP_KEY= > .env
      - php artisan key:generate
      - vendor/bin/phpunit
